<a href="https://colab.research.google.com/github/Jennas-Lee/highschool-portfolio-2021/blob/master/BigData/2021.04.13/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2021-04-13

In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [13]:
d = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [5, 6, 7, 8, 9]])
print(arr2[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [14]:
d[1:, 3]

array([5, 8])

In [16]:
d.shape

(3, 5)

In [20]:
e = np.array([2, 3, 4, 5, 6])
e.shape

(5,)

In [21]:
d.dtype

dtype('int64')

In [27]:
data = np.arange(1, 5)
data.dtype
data.shape
data.astype('float64')

array([1., 2., 3., 4.])

In [30]:
b = np.zeros((2, 10))
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [33]:
c = np.ones((2, 10))
c.shape
c.dtype

dtype('float64')

In [36]:
f = np.arange(2, 10)
f

array([2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
g = np.ones((2, 3))
g

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
# transpose : 행과 열을 바꿈

h = np.transpose(g)
h

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
arr1 = np.array([[2, 3, 4], [6, 7, 8]])
arr2 = np.array([[12, 23, 24], [36, 47, 58]])

arr1 + arr2

array([[14, 26, 28],
       [42, 54, 66]])

In [43]:
arr1 * arr2

array([[ 24,  69,  96],
       [216, 329, 464]])

In [44]:
arr1 / arr2

array([[0.16666667, 0.13043478, 0.16666667],
       [0.16666667, 0.14893617, 0.13793103]])

In [47]:
arr2 % arr1

array([[0, 2, 0],
       [0, 5, 2]])

In [48]:
arr3 = np.array([100, 200, 300])
arr1.shape
arr3.shape
arr1 + arr3

array([[102, 203, 304],
       [106, 207, 308]])

In [53]:
arr4 = np.arange(1, 11)
arr4
arr4.shape
arr1.shape
arr1 + arr4

ValueError: ignored

In [54]:
arr5 = np.array([[9], [3]])
arr5.shape
arr1

array([[2, 3, 4],
       [6, 7, 8]])

In [55]:
arr1 + arr5

array([[11, 12, 13],
       [ 9, 10, 11]])

파이썬 데이터 분석 패키지
* `Numpy` : 배열 계산 기능, 반올림, 버리기 기능
* `Pandas` : 데이터프레임으로 데이터 입력, 가공, describe, groupby
* `Matplotlib` : 그래프 그리기, plot, hist, bar
* `Scipy` : 통계분석

In [58]:
from google.colab import files
uploaded = files.upload()

Saving quest.csv to quest.csv


In [61]:
import numpy as np

quest = np.loadtxt('quest.csv', delimiter=',', dtype=np.int64)
print(quest)

[[1 2 1 2 2]
 [1 3 2 3 2]
 [1 4 3 3 3]
 [2 5 4 4 4]
 [2 5 6 2 5]
 [3 6 4 2 5]
 [3 5 4 1 6]
 [3 5 5 1 3]]


In [67]:
# 각 행들의 합을 구함

a = quest.sum(axis=1)
print(a)

# 각 열들의 합을 구함

b = quest.sum(axis=0)
print(b)

[ 8 11 14 19 20 20 19 17]
[16 35 29 18 30]


In [72]:
# 전체 성분의 평균
# 데이터의 평균

quest.mean()
quest.min()
quest.max()
quest.cumsum()
quest.cumprod()

array([                 1,                  2,                  2,
                        4,                  8,                  8,
                       24,                 48,                144,
                      288,                288,               1152,
                     3456,              10368,              31104,
                    62208,             311040,            1244160,
                  4976640,           19906560,           39813120,
                199065600,         1194393600,         2388787200,
              11943936000,        35831808000,       214990848000,
             859963392000,      1719926784000,      8599633920000,
           25798901760000,    128994508800000,    515978035200000,
          515978035200000,   3095868211200000,   9287604633600000,
        46438023168000000, 232190115840000000, 232190115840000000,
       696570347520000000])

In [73]:
# 인덱싱을 활용해 5보다 큰 수만 가져오기

quest[quest > 5]

array([6, 6, 6])

In [74]:
# 5보다 큰 숫자를 만점인 7점으로 바꾸기

quest[quest > 5] = 7
quest

array([[1, 2, 1, 2, 2],
       [1, 3, 2, 3, 2],
       [1, 4, 3, 3, 3],
       [2, 5, 4, 4, 4],
       [2, 5, 7, 2, 5],
       [3, 7, 4, 2, 5],
       [3, 5, 4, 1, 7],
       [3, 5, 5, 1, 3]])